// <auto-generated />
using System;
using System.Numerics;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using juego_impostor_backend.Shared.Persistence;

#nullable disable

namespace juegoimpostorbackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250604114704_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("juego_impostor_backend.Features.Categorias.Domain.Entities.CategoriaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("juego_impostor_backend.Features.Categorias.Domain.Entities.SubCategoriaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<BigInteger>("IdCategoria")
                        .HasColumnType("numeric");

                    b.Property<string>("SubCategoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SubCategorias");
                });

            modelBuilder.Entity("juego_impostor_backend.Features.IniciarPartida.Domain.Entities.PalabraSecretaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<BigInteger>("IdCategoria")
                        .HasColumnType("numeric");

                    b.Property<BigInteger>("IdSubCategoria")
                        .HasColumnType("numeric");

                    b.Property<string>("Palabra")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PalabrasSecretas");
                });
#pragma warning restore 612, 618
        }
    }
}
